#!/bin/zsh
SETUP_DIR="${ZDOTDIR:-~}/.zshconfig/packages"

for source in ${ZSHCONFIG_PACKAGE_SOURCES//,/ }
do
  if [ $source = "brew" ]; then
    for script in $SETUP_DIR/brew/*.sh; do
      source $script
    done

    packages=($(cat $SETUP_DIR/brew/packages))
    [ ${#packages[@]} -gt 0 ] &&  brew install ${packages[@]}
  fi

  if [ $source = "apt" ]; then
    for script in $SETUP_DIR/apt/*.sh; do
      source $script
    done

    packages=($(cat $SETUP_DIR/apt/packages))
    [ ${#packages[@]} -gt 0 ] && sudo apt update && sudo apt install ${packages[@]}
  fi

  if [ $source = "github" ]; then
    packages=($(cat $SETUP_DIR/github/packages))
    for package in ${packages[@]}; do
      package_name = $(echo $package | cut -d'/' -f2)
      [ -d .packages/$package_name ] && gh repo clone $p ackage "${ZSHCONFIG_PACKAGE_DIR:-.packages}/$package_name"
    done
    [ ${#packages[@]} -gt 0 ] && gh repo clone ${packages[@]}
  fi
done
